apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: swati599/backend-app:10
          ports:
            - containerPort: 3500
          envFrom:
            - configMapRef:
                name: app-config
          env:
            - name: MONGO_CONN_STR
              value: "mongodb://mongo-service:27017/tasksdb"
            - name: USE_DB_AUTH
              value: "false"
            - name: PORT
              value: "3500"
